tiledbsoma v1.16.0 (#7)
* updated v1.16.0

* MNT: Re-rendered with conda-build 25.1.2, conda-smithy 3.47.0, and conda-forge-pinning 2025.03.10.16.49.26

* Replace patch with new flag SPDLOG_LINK_SHARED to link spdlog

* tiledbsoma/soma/span/span.hpp is no longer present

* MNT: Re-rendered with conda-build 25.1.1, conda-smithy 3.47.0, and conda-forge-pinning 2025.03.12.19.21.36

* Fix includes for thread_pool.h

Error occurs on osx-* but not linux-*

 │ │   In file included from src/tiledbsoma/fastercsx.cc:19:
 │ │   In file included from $PREFIX/include/tiledbsoma/utils/fastercsx.h:21:
 │ │   $PREFIX/include/tiledbsoma/utils/parallel_functions.h:17:10: fatal error: 'thread_pool/thread_pool.h' file not found
 │ │      17 | #include <thread_pool/thread_pool.h>
 │ │         |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
 │ │   1 error generated.

* Regenerate `thread_pool.h` patch with `git diff`

* Bump to somacore 1.0.28

* Ensure proper visibility settings for CLI executable

* Remove -fvisibility-inlines-hidden from default compiler flags

* Revert "Ensure proper visibility settings for CLI executable"

This reverts commit 1142363bba4f53306f6543b50111b4122eba415d.

* Add debug compiler flags to troubleshoot memory error

* Install libsanitizer in the test section

* Add patch to fix memory error

* Use std::format in patch for 1.16.0

* Remove debugging flags

* Test that libspdlog is dynamically linked

* Only test for libspdlog linking when build and target platforms match

* Minimize customizations

* Confirmed that linux builds also need thread_pool patch

---------

Co-authored-by: John Blischak <jdblischak@gmail.com>
Co-authored-by: John Kerl <kerl.john.r@gmail.com>